[Actar]
LookUp: ./Calibrations/Actar/LT.txt
PadAlign: ./Calibrations/Actar/Outputs/gain_matching_s2029.txt

[Silicons]
IsEnabled: true
%Paths: ./Calibrations/Silicons/Outputs/f0.txt,
%       ./Calibrations/Silicons/Outputs/f1.txt,
%       ./Calibrations/Silicons/Outputs/l0.txt,
%       ./Calibrations/Silicons/Outputs/r0.txt,
Paths: ./Calibrations/Silicons/Outputs/s2029_f0_redo.dat,
       ./Calibrations/Silicons/Outputs/s2384_f1.dat,
       ./Calibrations/Silicons/Outputs/s2029_l0_redo.dat,
       ./Calibrations/Silicons/Outputs/s2029_r0_redo.dat,

[Modular]
%No calibrations applied
