[DataManager]
%Runs: 49,50
Runs: 49, ..., 65
Exclude: 25, 28, 31, 32, 33, 34, 62
%Manual: /home/artemis/ACTAR/S2029/Macros/Outputs/funEvts_many_clusters.txt
Manual: PostAnalysis/Macros/Outputs/events_l1_veryLowQevents.dat
%Manual: PostAnalysis/Macros/Outputs/events_pid_l1_lowQ_alphas.dat

[Raw]
TreeName: ACTAR_TTree
Path: ./RootFiles/Raw/
Begin: Tree_Run_
End: _Merged
%End: 

[Cluster]
TreeName: GETTree
Path: ./RootFiles/Cluster/
Begin: Clusters_Run_

[Data]
TreeName: VXITree
Path: ./RootFiles/Data/
Begin: Data_Run_

[Filter]
TreeName: GETTree
Path: ./RootFiles/Filter/
Begin: Filter_Run_

[Merger]
TreeName: ACTAR_Merged
Path: ./RootFiles/Merger/
Begin: Merged_Run_

% [Corrector]
% TreeName: ACTAR_Merged
% Path: ./RootFiles/Corrector/
% Begin: Corrected_Run_
